export const mbbrKeyLabels: Record<string, string> = {
  firstStage: "First Stage",
  secondStage: "Second Stage ",
  effluentConc: "Effluent Concentration",
  bodRemovalTank: "BOD Removal Tank",
  nitrificationTank: "Nitrification Tank",
  salr: "SALR",
  carrierFill: "Carrier Fill (%)",
  waterLevel: "Water Level (m)",
  carrierSurfaceArea: "Carrier Surface Area (m²/m³)",
  lengthWidthRatio: "Length-to-Width Ratio",
  flowRate: "Flow Rate (m³/d)",
  infBOD: "Influent BOD (mg/L)",
  infTKN: "Influent TKN (mg/L)",
  targetEffPercBOD: "Target BOD Removal (%)",
  targetEffPercTKN: "Target TKN Removal (%)",
  effluentBOD: "Effluent BOD (mg/L)",
  effluentTKN: "Effluent TKN (mg/L)",
  mediaVolume: "Media Volume (m³)",
  mediaSurfaceArea: "Media Surface Area (m²)",
  tankVolume: "Tank Volume (m³)",
  loadingRate: "Loading Rate (kg/m³·d)",
  width: "Tank Width (m)",
  length: "Tank Length (m)",
};
