export const septicTankKeyLabels: Record<string, string> = {
  numberOfUsers: "Estimated Number of Users",
  waterConsumption: "Water Consumption Per Person  (L)",
  waterDepth: "Water Depth (m)",
  allowanceDepth: "Allowance Depth (m)",
  sludgeSpecs: "Sludge Characteristics",
  desludgingPeriod: "Estimated period between desludging (years)",
  accumulationRate: "Sludge and scum accumulation rate (L/person)",
  sizingFactor: "Sizing factor",
  calculatedInfo: "Calculated Operational Parameters",
  retentionTime: "Estimated Retention Time (hours)",
  septicTankVolume: "Estimated Septic Tank Volume (m³/tank)",
  sludgeVolume: "Estimated Sludge Volume (m³)",
  totalSepticTankVolume: "Total Septic Tank Volume (m³)",
  tankWidth: "Tank Width (m)",
  firstTankLength: "First Compartment Length (m)",
  secondTankLength: "Second Compartment Lenth (m)",
  tankDepth: "Tank Depth (m)",
};
