export const uasbKeyLabels: Record<string, string> = {
  parameters: "Parameters",
  targetEffluent: "Target Effluent",
  estGasProduction: "Estimated Gas Production",
  flowRate: "Flow Rate (m³/d)",
  infCOD: "Influent COD (mg/L)",
  olr: "Organic Loading Rate (kg COD/m³ d)",
  upflowVelocity: "Upflow Velocity (m/h)",
  codRemoval: "COD Removal (%)",
  methaneYield: "Methane Yield (m³ CH₄/kg COD)",
  methaneFraction: "Methane Fraction in Biogas",
  massCODLoad: "COD Loading (kg/d)",
  massCODRemoved: "Amount of COD Removed (kg/d)",
  volume: "Volume (m³)",
  hrt: "Hydraulic Retention Time (h)",
  crossSectionalArea: "Cross Sectional Area (m²)",
  height: "Water Depth (m)",
  diameter: "Diameter (m)",
  methaneFlow: "Methane Flow (m³/d)",
  biogasFlow: "Biogas Flow based on CH₄ Fraction (m³/d)",
  gasLoading: "Gas Loading (m³ /m² d)",
};
